### ISSUE TITLE
Use package in MoH-Mali CHW and learn from it

### ISSUE THREAD

**Issue by Marina-Kenf** [medic/cht-stock-monitoring-workflow#13]
[config-moh-mali-chw#890](https://github.com/medic/config-moh-mali-chw/issues/890)

**Comment by Marina-Kenf** [comment]
Here is a summary of key feedback received from MoH Mali:

- [ ]  Rename the stock count form as "Fiche de stock"
- [ ] Add the expiry date while doing the inventory 
- [ ] Use `pills` as unit of count of drugs, rather that `tablets`: This is justified by the fact that drugs are dispensed by pills during care provision.

With this added, MoH is willing to use the package as an MPV, followed by a cycle of improvement based on feedback from the field.

cc @inromualdo - add anything missed out. 
Are you solving this here or as a new ticket on config-moh-mali-chw?

**Comment by inromualdo** [comment]
There is one more: Add number of set in item (Numero de lot)
There are other changes which are config updates. I will add them in a new config-moh-mali-chw ticket. For the others, I create a ticket for each (#26, #27, #28), since we cannot do everything at once

**Comment by Marina-Kenf** [comment]
So please close this if nothing more is expected from it.
