### ISSUE TITLE
stock monitoring PM feedbacks

### ISSUE THREAD

**Issue by falmataHassan** [medic/cht-stock-monitoring-workflow#20]
[Feedbacks](https://docs.google.com/presentation/d/1jJ64DVb6yJ1Tbs0Yi4z1JCHl-E730ozDbN8u1GDaeYg/edit#slide=id.g21c746fdc4f_0_109)

**Comment by falmataHassan** [comment]
- [ ] Contact summary
- [ ]  Add translations in french
- [ ] Display all items in summary section

**Comment by Marina-Kenf** [comment]
@falmataHassan are you making the changes (1) on the package directly or (2) manually in the configuration of MoH Mali?
Let's keep track on this repo only (1). If it's (2) do we intent to add in the package? cc @inromualdo

**Comment by falmataHassan** [comment]
@Marina-Kenf, I'm making the changes manually in Moh's configuration. I don't think they will be included in the package.
cc @inromualdo

**Comment by inromualdo** [comment]
@falmataHassan , this issue should be in the moh-mali chw repo.
cc: @Marina-Kenf

**Comment by Marina-Kenf** [comment]
@inromualdo are there plans to also make the same changes in the package or it's not relevant?

**Comment by inromualdo** [comment]
> @inromualdo are there plans to also make the same changes in the package or it's not relevant?

It's not relevant. Some issues should be fix from moh-mali repo. For the others that needed the package update we will create a separate ticket here.

**Comment by Marina-Kenf** [comment]
Thanks - so let's close this ticket.

**Comment by Marina-Kenf** [comment]
> It's not relevant. Some issues should be fix from moh-mali repo

How to we track this if we happen to update the package in this project?
