### ISSUE TITLE
Add the ability to create different variant of an item

### ISSUE THREAD

**Issue by inromualdo** [medic/cht-stock-monitoring-workflow#8]

**Comment by Marina-Kenf** [comment]
@inromualdo for which quarter is this planned? Can you add the corresponding label?

**Comment by inromualdo** [comment]
> @inromualdo for which quarter is this planned? Can you add the corresponding label?

Done.

**Comment by inromualdo** [comment]
@Marina-Kenf , I removed this for Q3, because the feature is not requested at the moment.

**Comment by Marina-Kenf** [comment]
Are you shifting this to Q4 or Q1-2024?

**Comment by Marina-Kenf** [comment]
Let close this as not part of the updated roadmap.
